### ISSUE TITLE
notifyDataSetChanged not working

### ISSUE THREAD

**Issue by vikskod** [takaaki7/ArrayPagerAdapter#1]
I want to change background of fragment which is on viewpager but it shows effect after 2-3 fragment moves. Is there any solution for this problem?

**Comment by takaaki7** [comment]
@viksoffice Thank you for being interested in this project.
What does "it shows effect after 2-3 fragment moves." mean?
Do you mean, you can't change background of view even if calling notifyDataSetChanged and swipe view pager 2, 3 times?
Could you show me a sample code to reproduce the problem?

**Comment by viksoffice** [comment]
Background of view is changing after 2,3 times swiping.

**Comment by vikskod** [comment]
Please look at here https://github.com/viksoffice/Android-Dynamic-Viewpager
In above sample app i want to change background but it changing after 2 times swipe.

**Comment by takaaki7** [comment]
@viksoffice Thank you for uploading the project.
I understand the cause of the problem.
You write code about changing background color in onCreateView of fragment. But ViewPager doesn't recreate fragment when being called `notifyDataSetChanged()`, so onCreateView is not called.
This library supports 'notifyDataSetChanged' only for changing order of items or size of list.
No matter whether using this library or not, if you want recreating fragment on calling `notifyDataSetChanged` , you have to override `getItemPosition()` method of adapter and return appropriate value.

I think there is 3 solutions,
1. If you don't mind a little decrease in performance, returning POSITION_NONE always make ViewPager recreate all fragment when `notifyDataSetChanged()` is called. So view will be redrawed and background color will change.
2. Making a method that recreate items in adapter. Maybe you can make it in custom adapter of your project or this library. If you make pull-request, I will merge it. 
3. Using event bus or content-provider, make activity post `Changing background color event` , and handle it in fragment to change view's behavior.

**Comment by vikskod** [comment]
overriding on `getItemPosition()` will take more compilation procedure and time for viewpager which is not good solution. I'll try with `Bus`. 
Thank you for your help
VIkash Parajuli
vparajuli819@gmail.com

**Comment by shriomtri** [comment]
@viksoffice  i'm also stuck with updating viewpager , can you help me with you code for bus

**Comment by vikskod** [comment]
@jay006 bro see https://github.com/viksoffice/Android-Dynamic-Viewpager
