### ISSUE TITLE
Adding an item at a given position

### ISSUE THREAD

**Issue by harryskim** [takaaki7/ArrayPagerAdapter#2]
Hi Takaaki7, 

Thank you so much for posting this! I gave it try and it works like a charm :) I was wondering if there is an easy way to add an item at a given position using your library (e.g. add(T item, int position)). 

I am trying to insert an item to the beginning of an ArrayList while users swipe left. Please let me know, and I hope you are having a great day!

Best,
Harry

**Comment by takaaki7** [comment]
@harryskim 
Thank you for using this library.
Currently there is no method to do it.
But maybe today or tomorrow, I will add that method if it isn't difficult.

**Comment by takaaki7** [comment]
@harryskim 
I added that method in https://github.com/takaaki7/ArrayPagerAdapter/commit/c1f19db6aac4965cbe665d546ab3bd4877adee0c

If you have any problems, please let me know.

**Comment by harryskim** [comment]
Thank you so much! I just checked, and it's working great :) Really appreciate it!
