### ISSUE TITLE
Gradle Build Error

### ISSUE THREAD

**Issue by airowe** [takaaki7/ArrayPagerAdapter#4]
Trying to compile your project through gradle is not working for me.

**Comment by joaquinTop** [comment]
Try this @airowe : 
--
compile 'com.nakama.arraypageradapter:arraypageradapter:0.1.1'

**Comment by takaaki7** [comment]
@joaquinTop Thank you for your comment.
@airowe I'm sorry, I haven't noticed your message. If you still have problem, I will research the problem.

**Comment by chetandalal1993** [comment]
I am also facing the same issue. Unable to build gradle for 0.1.3
